
name: Deploy to Dev

on:
  push:
    branches:
    - madhu-sample-dev 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/my-app:${{ github.sha }}

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig \
          --region ap-southeast-1 \
          --name bq-eks-cluster-dev

    - name: Update deployment
      run: |
        kubectl set image deployment/my-app \
        app=${{ steps.login-ecr.outputs.registry }}/my-app:${{ github.sha }}

    - name: Wait for rollout
      run: |
        kubectl rollout status deployment/my-app