replicaCount: 1

image:
  pullPolicy: Always

result:
  image:
    repository: <account>.dkr.ecr.ap-southeast-1.amazonaws.com/bq-eks-repo-prod
    tag: latest

  service:
  type: NodePort
  port: 8081
  targetPort: 80
  nodePort: 31001

vote:
  image:
    repository: <account>.dkr.ecr.ap-southeast-1.amazonaws.com/bq-eks-repo-prod
    tag: latest

    service:
    type: NodePort
    port: 8080
    targetPort: 80
    nodePort: 31000

worker:
  image:
    repository: <account>.dkr.ecr.ap-southeast-1.amazonaws.com/bq-eks-repo-prod
    tag: latest