replicaCount: 1

image:
  pullPolicy: Always

result:
  image:
    repository: <account>.dkr.ecr.ap-southeast-1.amazonaws.com/bq-eks-repo-prod
    tag: latest

vote:
  image:
    repository: <account>.dkr.ecr.ap-southeast-1.amazonaws.com/bq-eks-repo-prod
    tag: latest

worker:
  image:
    repository: <account>.dkr.ecr.ap-southeast-1.amazonaws.com/bq-eks-repo-prod
    tag: latest