apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: mightycapstone   # 👈 ensure it matches your namespace
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - name: postgres
    port: 5432       # service port inside cluster
    targetPort: 5432 # container port from db-deployment

