apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-v1-deployment
  namespace: mightycapstone
  labels:
    app: result-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-v1
  template:
    metadata:
      labels:
        app: result-v1
    spec:
      containers:
      - name: result
        image: 255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/mightycapstonevoting:result-v1
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: DB_HOST
          value: db-service
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
