apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: {{ .Release.Name }}-result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetPort }}
    nodePort: {{ .Values.result.service.nodePort }}
  selector:
    app: result
