apiVersion: v1
kind: Service
metadata:
  name: vote-service
  # namespace: mightycapstone
  labels:
    app: vote
spec:
  type: LoadBalancer   # 👈 no nodePort here
  selector:
    app: vote
  ports:
  - name: http
    port: 8080       # external port exposed by ELB
    targetPort: 80   # container port

