apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: mightycapstone
  labels:
    app: vote
  name: {{ .Release.Name }}-vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: {{ .Values.vote.service.port }}
    targetPort: {{ .Values.vote.service.targetPort }}
    nodePort: {{ .Values.vote.service.nodePort }}
  selector:
    app: vote
  ports:
  - name: http
    port: 8080       # external port exposed by ELB
    targetPort: 80   # container port

