apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  # namespace: mightycapstone
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: 255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/mightycapstonevoting:worker-v2
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: DB_HOST
          value: db-service


